return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "actionlint",
      "ansible-language-server",
      "antlers-language-server",
      "bash-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dot-language-server",
      "eslint_d",
      "hadolint",
      "html-lsp",
      "intelephense",
      "php-debug-adapter",
      "phpstan",
      -- "pint",
      -- "phpcs",
      "php-cs-fixer",
      "prettierd",
      "prettier",
      "pyright",
      "rustywind",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "lua-language-server",
      "shellcheck",
      "shfmt",
      "intelephense",
      "google-java-format",
      "java-debug-adapter",
      "java-test",
    },
  },
}
